### ISSUE TITLE
Unable to access Sales Performance Data File

### ISSUE THREAD

**Issue by juliafsuzuki** [keithmcnulty/peopleanalytics-regression-book#11]
Hello - I've never accessed data file stored in GitHub so this might be a user error, but I am not able to read the csv file for the Sales Performance Rating exercise.

Below is the set of codes I ran in R studio. I've also attached the screen print of the output.

Thank you for your assistance!

--

urlFile <- "https://github.com/keithmcnulty/peopleanalytics-regression-book/tree/master/presentations/employee_performance.csv"
employee_performance <- read.csv(urlFile)
head(employee_performance)
![ScreenShot](https://user-images.githubusercontent.com/77695324/105083620-2d1bf080-5a63-11eb-80ac-59f2d2f14990.PNG)

**Comment by keithmcnulty** [comment]
You need to access the raw data file.   You can do this by viewing the csv file in GitHub, then clicking on ‘Raw’ view and then using the url that this takes you to.

**Comment by juliafsuzuki** [comment]
It worked! Thank you.
