### ISSUE TITLE
Section 4.2.2 Minimising the error

### ISSUE THREAD

**Issue by ritsu1997** [keithmcnulty/peopleanalytics-regression-book#12]
"The average of our residuals" is listed as one of the examples of the evaluation criteria for a good-fit.

But, we can make it  as small as we want because drawing a line very far above the data points will give negative residuals. The farther above, the larger the absolute values. 

So, technically, the minimization of the average of residuals doesn't have a solution. The smallness of the quantity also fails to represent how successfully our regression line fits the data points. 

I know this is a very subtle point because it is only given to demonstrate that there are several other criteria that can be used, but I think it might be a little bit confusing for some people. So, maybe you can explain why we use the average of squares of the residuals rather than the average of the residuals.

Anyway, this is a great book! I'm looking forward to having a hard copy in the summer.

**Comment by keithmcnulty** [comment]
Yes, as 'negative' as you want is I guess the point you are making.  In reality, what is meant is the absolute value of the sum of the residuals, which different from the sum of the absolute values of the residuals.  But anything with absolute values in it was very challenging to work out how to minimize in the early 20th century, as opposed to squared terms which calculus could easily handle.  Thanks for raising.

**Comment by ritsu1997** [comment]
Thanks for a quick reply.

So, even if we use the absolute value of the sum of the residuals (AVSR), I guess it's not a very good criterion because for any (non-intercept) coefficients we can obtain zero AVSR by manipulating the intercept.

Say, first try y = a + bx, and  suppose it turns out the sum of the residuals is = r (i.e., AVSR = |r|). Then, y = (a + r/n) + bx (with n = sample size) will produce a zero AVSR since r = sum(y - (a + bx)) by definition. For example, set b = 0 and a = mean(y), then the AVSR is zero. This holds for any a and b, so there are always infinitely many solutions in the minimization problem of AVSR. So, maybe it is not really a reasonable criterion to be listed as like a valid one? 

Sorry if this is like nitpicking. Just trying to improve though.

**Comment by ritsu1997** [comment]
My pleasure! Thank you again for a really great book.
