### ISSUE TITLE
Typo in 6.2.1 

### ISSUE THREAD

**Issue by aliaamiri** [keithmcnulty/peopleanalytics-regression-book#15]
The `family = "binomial"` argument for modeling `A_simple` using `glm` is not provided, so, it changes the result.
Best Regards

**Comment by keithmcnulty** [comment]
Thank you for alerting me to this.  I will correct it in the online book now. Many thanks!

**Comment by aliaamiri** [comment]
You're welcome. Thank you for the fabulous book.
