### ISSUE TITLE
Chapter 2 Data Exercises Solutions & Questions

### ISSUE THREAD

**Issue by cjoanc27** [keithmcnulty/peopleanalytics-regression-book#19]
As someone with limited coding experience, I used Chapter 2 as a self-learning guide and managed to cut my teeth on R. Sharing my first attempt to create solutions using R Markdown, in case there are other readers at the beginner level like myself. Also hoping to hear any best practices that I'm not aware of yet.  

For exercise 12, anyone has alternative solutions to creating the 5-level grading logic? Thanks!

```
new_ugtests <- ugtests %>% 
  mutate(finalgrade = case_when (ugtests$Final <= 60 ~ 1,
                                 between(ugtests$Final,60,120) ~2,
                                 between(ugtests$Final, 120,180) ~3,        
                                 between(ugtests$Final, 180,240) ~4,
                                 between(ugtests$Final, 240,300) ~5))
str(new_ugtests)
```

[Chapter 2.pdf](https://github.com/keithmcnulty/peopleanalytics-regression-book/files/7964735/Chapter.2.pdf)

**Comment by keithmcnulty** [comment]
Thanks for posting your solutions - its great to see that you have tacked them so well based on your initial learning.   Your solution to Exercise 12 is just fine.  An alternative option, with less typing, is to use the `cut()` function, which turns your values into categories according to the cutoff points specified.

```
new_ugtests <- ugtests %>% 
  dplyr::mutate(
    finalgrade = cut(Final, c(0, 60, 120, 180, 240, 300), labels = FALSE)
  )
```

Of if you didn't want to use `dplyr` you could simply use:

```
ugtests$finalgrade <- cut(ugtests$Final, c(0, 60, 120, 180, 240, 300), labels = FALSE)
```

If you are interested in why I specified `labels = FALSE` take a look at the labels when you set this to `TRUE`.

Would you mind if I link to your solutions on the solutions website?  (Right now there are only a few posted solutions for Chapter 3), and would you mind if I link to your solutions on social media by way of encouraging others to work on these exercises?

Many thanks!

**Comment by cjoanc27** [comment]
Hi Keith, 

Thanks for your reply - your solutions are very helpful. 

Please feel free to link my work to the solutions website and to LinkedIn. I'd be very happy to connect with other learners and experts as I move forward to the following chapters. 

Here is my [LinkedIn ](https://www.linkedin.com/in/joanne-cao/) - I've been a follower but just sent you an invite to connect. Thanks!

Regards,
Jo

**Comment by keithmcnulty** [comment]
Hi Jo, Just FYI your solutions are now available at https://solutions.peopleanalytics-regression-book.org. Note that the link points straight to the pdf file you uploaded initially in this thread, so if you want to make changes or update that file, you can do so by editing that initial post and replacing the uploaded file and it will flow through to the solutions site. Many thanks!
