### ISSUE TITLE
Chapter 3 Solutions & Questions

### ISSUE THREAD

**Issue by cjoanc27** [keithmcnulty/peopleanalytics-regression-book#20]
Posting my attempt for data exercises 1-8 in Chapter 3. 

Also two questions as I moved to Chapter 4. 
1. (Chapter 3) Chi-square - when the contingency table has 3*3 or more, are there follow-up tests to further ascertain the specific association, after we find the chi-square statistic significant?

2. (Chapter 4) Dummy code - should it not be (k-1) number of dummy variables when k is the level of the categorical variable, so that one of the levels serves as the baseline? Trying to understand why the `dummies` package in the chapter would return 3 dummy variables for 3 types of make?
```
library(dummies)
(dummy_vehicle <- dummies::dummy("make", data = vehicle_data))
```

Thanks!
Jo

[Chapter 3 1-8.pdf](https://github.com/keithmcnulty/peopleanalytics-regression-book/files/8018815/Chapter.3.1-8.pdf)

**Comment by keithmcnulty** [comment]
Thanks for your answers Jo - I will post them to the solutions site.

Re your questions:

1.  This is commonly called a 'post-hoc' analysis.  If you do searches on the web for 'Chi square post hoc' you can see a few options for how to do this in R.  
2. The baseline category will be determined inside the model.  The `dummies` package merely acts as a convenience tool to create the dummy variables.  When those are actually fed into the model code, it will automatically select one of those to be a baseline.  You'll see more of this in Chapter 5.  Most convenient modeling functions do not require us to explicitly create dummies, and they have built in code to do this.  But I still do it in this book to help people understand how categorical variables are handled by regression models.

Hope that helps!
