### ISSUE TITLE
Error: bs4_book not an exported object

### ISSUE THREAD

**Issue by jrcarob** [keithmcnulty/peopleanalytics-regression-book#3]
Dear Mr. Mcnulty:

Why I got the following error?

Error: 'bs4_book' is not an exported object from 'namespace:bookdown'
Please delete _main.Rmd after you finish debugging the error.
Execution halted

Seems that the execution creates automatically the _main.Rmd file. I updated all the packages, installed those missed but still generates the same error.

Thanks for your support

**Comment by jrcarob** [comment]
Problem solved! It was a package updating issue.

**Comment by keithmcnulty** [comment]
Closing
