### ISSUE TITLE
Section 5.3.1 Understanding Results

### ISSUE THREAD

**Issue by duncanwil** [keithmcnulty/peopleanalytics-regression-book#33]
In section 5.3.1 you work through and example relating to sales performance and promotion prospects. Everything is clear, except where you conclude that "All else being equal, customer ratings have a significant negative effect on the likelihood of promotion, with one full rating higher associated with 67% lower odds of promotion" based on these values. I am not sure what value I am expecting there but I don't see how you arrived at 67%

## customer_rate  -1.11213130 2.121881e-02 3.288573e-01

Similarly, a little lower down, based on values of  ## customer_rate 1.141645e-01 7.793018e-01 you say, "and every additional point in customer rating decreases the odds of promotion by between 22% and 89%" For this one, it seems to me that the values should be -89% and -92%

Otherwise, I am finding this book really useful for me! So, thanks for that!

Duncan

**Comment by keithmcnulty** [comment]
Hi Duncan.

On the first example note that 3.288573e-01 is approximately equal to 0.33
= 1 - 0.67.  Hence 67% lower odds.

Hopefully you can see how the confidence interval interpretation is derived
in a similar way.

Hope this helps!

**Comment by duncanwil** [comment]
Thanks Keith, I will confess, I misread that 3.288... value and your response makes perfect sense, of course

Best wishes

Duncan
