### ISSUE TITLE
Section 4.2.4 - Measuring The Fit Of The Model

### ISSUE THREAD

**Issue by sasnnm** [keithmcnulty/peopleanalytics-regression-book#4]
I have two related though distinct questions. I hope, as someone diving deep into the text, I might find clarifications others will find useful as well.

1. I wonder where the number **1457.6** comes from and how.

In the text for this section, it reads: "Therefore Var(y) represents the mean sum of squares error of a random model. This calculates in this case to **1457.6**." Just a bit later then this sentence begins: "Therefore before we fit our model, we have an average error of **1574.21**...".

In R I can see that 1574.21 is correct:

```
#Measuring Fit
d$Final

#Average Error of Random Model
sum((d$Final - mean(d$Final))^2)/length((d$Final)) #[1] 1574.21

#Average Error of Fitted Model
sum(model$residuals^2)/length((model$residuals)) #[1] 398.347

#R-squared - our model explains 0.75 (or 75%) of the variance of our outcome
((sum((d$Final - mean(d$Final))^2)/length((d$Final))) - 
  (sum(model$residuals^2)/length((model$residuals)))) / 
    (sum((d$Final - mean(d$Final))^2)/length((d$Final))) #[1] 0.7469543
```

2. This portion is to clarify my understanding of the baseline statistics in play: Why is this TRUE?

```
> sum((d$Final - mean(d$Final))^2)/length((d$Final)) == 9/10*var(d$Final)
```

Specifically I am wondering how and why the product when multiplying by 9/10 results in the average error of the random model?

**Comment by keithmcnulty** [comment]
Thank you @sasnnm - on number 1 you spotted some old inline code that had been left uncorrected from a previous version of the chapter.  I have updated this now and sorry for the confusion.  Please check it aligns now.  

On 2, the left hand side of your equation is the mean sum of squares error of the random model, which is also the definition of the *population variance* of `d$Final`.  You'll recall from Section 3.1 that in R,`var(y)` calculates the *sample variance* of y.  To derive *population variance* from *sample variance* you multiply by (n-1)/n which is 9/10 in this case.  So both sides of your equation are different formulas for calculating the population variance.  It's reassuring that they agree :)

Please let me know if this makes sense and happy new year!

**Comment by sasnnm** [comment]
Thank you @keithmcnulty; and my apologies for the LinkedIn message. This is updated on my end. Love the book!
