### ISSUE TITLE
Ch.3 // Ex. 9: Using mu

### ISSUE THREAD

**Issue by sasnnm** [keithmcnulty/peopleanalytics-regression-book#5]
The solution you've provided is nearly identical to that I landed on below and I wonder if you might offer both as options? Or if there are more subtle distinctions between the two I'm not thinking of?

I've used the mu difference of ten as a function parameter instead of substracting from the x input:

```
> t.test(recent_yes$age, recent_no$age, alternative = "g", mu = 10)

	Welch Two Sample t-test

data:  recent_yes$age and recent_no$age
t = 5.2268, df = 105.15, p-value = 4.403e-07
alternative hypothesis: true difference in means is greater than 10
95 percent confidence interval:
 17.16282      Inf
sample estimates:
mean of x mean of y 
 62.68675  42.19188 
```

**Comment by keithmcnulty** [comment]
Thanks - added to solution!
