### ISSUE TITLE
Answer Key?

### ISSUE THREAD

**Issue by haras3** [keithmcnulty/peopleanalytics-regression-book#9]
Sorry if I somehow missed it...Do you have an answer key for the exercises at the end of each chapter?  I'm a noob and want to check my work.  Thanks for the book!

**Comment by keithmcnulty** [comment]
If certain questions get a lot of requests for solutions I will post something.   You’ll already find a small number of answers in this repo at https://keithmcnulty.github.io/peopleanalytics-regression-book/solutions/

If a specific question is troubling you you can post an issue and I can provide a POV or someone else in the community can comment.  Alternatively you could consider contributing a solution which would allow others to critique it.
